# Generated by Django 3.0.5 on 2023-01-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_heartdatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainStrokeDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('hypertension', models.IntegerField()),
                ('heart_disease', models.IntegerField()),
                ('ever_married', models.IntegerField()),
                ('work_type', models.IntegerField()),
                ('Residence_type', models.IntegerField()),
                ('avg_glucose_level', models.FloatField()),
                ('bmi', models.FloatField()),
                ('smoking_status', models.IntegerField()),
                ('stroke', models.IntegerField()),
            ],
            options={
                'db_table': 'BrainStrokeDatabase',
            },
        ),
        migrations.DeleteModel(
            name='HeartDataModel',
        ),
    ]
